apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: opaque
stringData:
  MYSQL_ROOT_PASSWORD: ZnVrbzA5cGhzdXJ4aG8=
  
---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-password
type: opaque
stringData:
  MYSQL_ROOT_PASSWORD: ZnVrbzA5cGhzdXJ4aG8=
  

