apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
 namespace: default
 name: wordpress-appflex-scaledobject
spec:
 scaleTargetRef:
   kind:          Deployment
   name:          wordpress-appflex
 pollingInterval: 20
 minReplicaCount: 1
 maxReplicaCount: 10
 advanced:
   restoreToOriginalReplicaCount: false
   horizontalPodAutoscalerConfig:
     behavior:
       scaleDown:
         stabilizationWindowSeconds: 300
         policies:
         - type: Percent
           value: 25
           periodSeconds: 60
 triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "70"
  - type: memory
    metadata:
      type: Utilization
      value: "50"
 
