apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-appflex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-appflex
  template:
    metadata:
      labels:
        app: wordpress-appflex
    spec:
      containers:
      - name: wordpress
        image: virtapp/wordpress-appflex:0.2
        resources:
            requests:
              memory: "1Gi"
              cpu: 1
            limits:
              cpu: 2
              memory: "2Gi"
        ports:
        - containerPort: 80
        env:
            - name: WORDPRESS_DB_HOST
              value: mariadb-mariadb-galera
            - name: WORDPRESS_DB_NAME
              value: appflex
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
 
---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-appflex
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: wordpress-appflex
    
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-route-appflex
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "session-route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    #nginx.ingress.kubernetes.io/canary: "true"
    #nginx.ingress.kubernetes.io/canary-weight: "60"
    #nginx.ingress.kubernetes.io/affinity-mode: persistent
    #nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    #nginx.ingress.kubernetes.io/proxy-connect-timeout: "300s"
    #nginx.ingress.kubernetes.io/proxy-send-timeout: "300s"
    #nginx.ingress.kubernetes.io/proxy-read-timeout: "300s"
    #nginx.ingress.kubernetes.io/send-timeout: "300"
    #nginx.ingress.kubernetes.io/client-body-buffer-size: "5m"
    #nginx.ingress.kubernetes.io/proxy-body-size: "5m"
spec:
  tls:
  - secretName: appflex
  rules:

  - host: appflex.io
    http:
      paths:
      - backend:
          serviceName: wordpress-appflex
          servicePort: 80
          
---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
 namespace: default
 name: wordpress-appflex
spec:
 scaleTargetRef:
   apiVersion:    apps/v1 
   kind:          Deployment
   name:          wordpress-appflex
 pollingInterval: 20
 minReplicaCount: 2
 maxReplicaCount: 10
 advanced:
   restoreToOriginalReplicaCount: false
   horizontalPodAutoscalerConfig:
     behavior:
       scaleDown:
         stabilizationWindowSeconds: 300
         policies:
         - type: Percent
           value: 25
           periodSeconds: 60
 triggers:
  - type: cron
    metadata:
      timezone: Asia/Jerusalem
      start: 0 8 * * *
      end: 0 23 * * *
      desiredReplicas: "3"
