apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-appflex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-appflex
  template:
    metadata:
      labels:
        app: wordpress-appflex
    spec:
      containers:
      - name: wordpress
        image: global-registry.virtapp.io/library/apache-appflex:0.9
        resources:
            requests:
              memory: "1Gi"
              cpu: 1
            limits:
              cpu: 2
              memory: "2Gi"
        ports:
        - containerPort: 80
        env:
            - name: WORDPRESS_DB_HOST
              value: mysql
            - name: WORDPRESS_DB_NAME
              value: appflex
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password         

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-appflex
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: wordpress-appflex


---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  namespace: default
  name: wordpress-appflex 
spec:
  scaleTargetRef:
    apiVersion:    apps/v1                           # Optional. Default: apps/v1
    kind:          Deployment                        # Optional. Default: Deployment
    name:          wordpress-appflex                 # Mandatory. Must be in the same namespace as the ScaledObject
  pollingInterval:  30                               # Optional. Default: 30 seconds
  cooldownPeriod:   60                               # Optional. Default: 300 seconds
  minReplicaCount:  1                                # Optional. Default: 0
  maxReplicaCount:  10                               # Optional. Default: 100
  fallback:                                          # Optional. Section to specify fallback options
    failureThreshold: 3                              # Mandatory if fallback section is included
    replicas: 6                                      # Mandatory if fallback section is included
  advanced:                                          # Optional. Section to specify advanced options
    restoreToOriginalReplicaCount: true              # Optional. Default: false
    horizontalPodAutoscalerConfig:                   # Optional. Section to specify HPA related options
      behavior:                                      # Optional. Use to modify HPA's scaling behavior
        scaleDown:
          stabilizationWindowSeconds: 60
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
  triggers:
  - type: prometheus
    metadata:
      # Required fields:
      serverAddress: http://prometheus-service.ingress-nginx.svc.cluster.local:8080
      metricName: nginx_ingress_controller_nginx_process_connections_total # Note: name to identify the metric, generated value would be `prometheus-http_requests_total`
      query: sum(rate(nginx_ingress_controller_nginx_process_connections_total[1m])) by (state)  # Note: query must return a vector/scalar single element response
      threshold: '5'
      # Optional fields:
      #namespace: monitoring  # for namespaced queries, eg. Thanos
 
 
