apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-appflex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-appflex
  template:
    metadata:
      labels:
        app: wordpress-appflex
    spec:
      containers:
      - name: wordpress
        image: global-registry.virtapp.io/library/apache-appflex:0.9
        resources:
            requests:
              memory: "1Gi"
              cpu: 1
            limits:
              cpu: 2
              memory: "2Gi"
        ports:
        - containerPort: 80
        env:
            - name: WORDPRESS_DB_HOST
              value: mysql
            - name: WORDPRESS_DB_NAME
              value: appflex
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password         

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-appflex
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: wordpress-appflex


---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  namespace: default
  name: wordpress-appflex 
spec:
  scaleTargetRef:
    apiVersion:    apps/v1                           # Optional. Default: apps/v1
    kind:          Deployment                        # Optional. Default: Deployment
    name:          wordpress-appflex                 # Mandatory. Must be in the same namespace as the ScaledObject
  pollingInterval:  30                               # Optional. Default: 30 seconds
  cooldownPeriod:   60                               # Optional. Default: 300 seconds
  idleReplicaCount: 0                                # Optional. Default: ignored, must be less than minReplicaCount 
  minReplicaCount:  1                                # Optional. Default: 0
  maxReplicaCount:  10                               # Optional. Default: 100
  fallback:                                          # Optional. Section to specify fallback options
    failureThreshold: 3                              # Mandatory if fallback section is included
    replicas: 6                                      # Mandatory if fallback section is included
  advanced:                                          # Optional. Section to specify advanced options
    restoreToOriginalReplicaCount: true/false        # Optional. Default: false
    horizontalPodAutoscalerConfig:                   # Optional. Section to specify HPA related options
      behavior:                                      # Optional. Use to modify HPA's scaling behavior
        scaleDown:
          stabilizationWindowSeconds: 60
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
  triggers:
  - type: cron
    metadata:
      desiredReplicas: "6"
      start: 10 * * * *
      end: 35 * * * *
      timezone: Asia/Jerusalem
