apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-appflex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-appflex
  template:
    metadata:
      labels:
        app: wordpress-appflex
    spec:
      containers:
      - name: wordpress
        image: global-registry.virtapp.io/library/apache-appflex:0.9
        resources:
            requests:
              memory: "1Gi"
              cpu: 1
            limits:
              cpu: 2
              memory: "2Gi"
        ports:
        - containerPort: 80
        env:
            - name: WORDPRESS_DB_HOST
              value: mysql
            - name: WORDPRESS_DB_NAME
              value: appflex
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password         

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-appflex
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: wordpress-appflex


---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
 namespace: default
 name: wordpress-appflex
spec:
 scaleTargetRef:
   kind:          Deployment
   name:          wordpress-appflex
 pollingInterval: 20
 minReplicaCount: 1
 maxReplicaCount: 10
 triggers:
  - type: cron
    metadata:
      desiredReplicas: "6"
      start: 10 * * * *
      end: 35 * * * *
      timezone: Asia/Jerusalem

