
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-virtapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-virtapp
  template:
    metadata:
      labels:
        app: wordpress-virtapp
    spec:
      containers:
      - name: wordpress
        image: virtapp/wordpress-virtapp:0.9
        #image: global-registry.virtapp.io/library/apache-php:7.2
        resources:
            requests:
              memory: "1Gi"
              cpu: 1
            limits:
              cpu: 4
              memory: "2Gi"
        ports:
        - containerPort: 80
        env:
            - name: WORDPRESS_DB_HOST
              value: mariadb-mariadb-galera
            - name: WORDPRESS_DB_NAME
              value: virtapp_io
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
      restartPolicy: Always
      nodeSelector: {}
        #node-role.kubernetes.io/master: "true"
 
 
---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-virtapp
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: wordpress-virtapp
  

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-route-virtapp
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "virtapp software"
    nginx.ingress.kubernetes.io/session-cookie-secure: "true"
    nginx.ingress.kubernetes.io/session-cookie-change-on-failure: "false"
    nginx.ingress.kubernetes.io/affinity-mode: "balanced"
    nginx.ingress.kubernetes.io/server-snippet: |
      expires 1M;
      add_header Cache-Control "public";
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Client-Cert $ssl_client_fingerprint;
      add_header Cache-Control "max-age=0, no-cache, no-store, must-revalidate";
      add_header X-Frame-Options SAMEORIGIN;
      add_header Strict-Transport-Security "max-age=31536000;includeSubdomains; preload";
      more_set_headers "server-tokens: GSLB Technologies"
      more_clear_headers "Server";
      more_set_headers "X-Frame-Options: Deny";
      more_set_headers "X-Xss-Protection: 1; mode=block";
      more_set_headers "X-Content-Type-Options: nosniff";
    nginx.ingress.kubernetes.io/enable-access-log: "false"
spec:
  tls:
  - secretName: virtapp
  rules:

  - host: virtapp.io
    http:
      paths:
      - backend:
          serviceName: wordpress-virtapp
          servicePort: 80
                    
---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
 namespace: default
 name: wordpress-virtapp
spec:
 scaleTargetRef:
   apiVersion:    apps/v1 
   kind:          Deployment
   name:          wordpress-virtapp
 pollingInterval: 20
 minReplicaCount: 2
 maxReplicaCount: 10
 advanced:
   restoreToOriginalReplicaCount: false
   horizontalPodAutoscalerConfig:
     behavior:
       scaleDown:
         stabilizationWindowSeconds: 300
         policies:
         - type: Percent
           value: 25
           periodSeconds: 60
 triggers:
  - type: cron
    metadata:
      timezone: Asia/Jerusalem
      start: 0 7 * * *
      end: 0 23 * * *
      desiredReplicas: "4"
