apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-virtapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-virtapp
  template:
    metadata:
      labels:
        app: wordpress-virtapp
    spec:
      containers:
      - name: wordpress
        image: global-registry.virtapp.io/library/apache-php:7.2
        resources:
            requests:
              memory: "1Gi"
              cpu: 1
            limits:
              cpu: 2
              memory: "2Gi"
        ports:
        - containerPort: 80
        env:
            - name: WORDPRESS_DB_HOST
              value: mysql
            - name: WORDPRESS_DB_NAME
              value: virtapp_io
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
 
---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-virtapp
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: wordpress-virtapp
    
    
---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
 namespace: default
 name: wordpress-virtapp
spec:
 scaleTargetRef:
   kind:          Deployment
   name:          wordpress-virtapp
 pollingInterval: 20
 minReplicaCount: 1
 maxReplicaCount: 6
 advanced:
   restoreToOriginalReplicaCount: false
   horizontalPodAutoscalerConfig:
     behavior:
       scaleDown:
         stabilizationWindowSeconds: 300
         policies:
         - type: Percent
           value: 25
           periodSeconds: 60
 triggers:
  - type: cron
    metadata:
      timezone: Asia/Jerusalem
      start: 0 8 * * *
      end: 0 18 * * *
      desiredReplicas: "3"
