apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-server
  labels:
    app: httpd-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-server
  template:
    metadata:
      labels:
        app: httpd-server
    spec:
      containers:
      - name: httpd-server
        image: manageiq/manageiq:kasparov-1
        ports:
          - name: http-port
            containerPort: 443
      restartPolicy: Always
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool

---

kind: Service
apiVersion: v1
metadata:
  name: httpd-server
spec:
  selector:
    app: httpd-server
  type: ClusterIP
  ports:
    - name: http-port
      port: 443
      targetPort: 8443
