kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: httpd-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: httpd-server
    spec:
      containers:
      - name: httpd-server
        image: httpd
        ports:
        - containerPort: 80
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
---

kind: Service
apiVersion: v1
metadata:
  name: httpd-server
spec:
  selector:
    app: httpd-server
  type: LoadBalancer
  ports:
    - name: httpd-server-port
      port: 8080
      targetPort: 80
