apiVersion: apps/v1
kind: Deployment
metadata:
  name: innovi-portal-argo
  labels:
    app: innovi-portal-argo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: innovi-portal-argo
  template:
    metadata:
      labels:
        app: innovi-portal-argo
    spec:
      containers:
      - name: innovi-portal-argo
        image: agentvi/innovi-portal:2.1.rc-2569
        envFrom: 
        - configMapRef:
            name: innovi-portal-config
        ports:
          - name: portal-port
            containerPort: 8082
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool


# innovi-portal service
---
apiVersion: v1
kind: Service
metadata:
  name: innovi-portal-argo
  namespace: default
  labels:
    app: "innovi-portal-argo"
  annotations: {}
    #cloud.google.com/neg: '{"ingress": true}'
    #beta.cloud.google.com/backend-config: '{"ports": {"8082":"innovi-portal-backendconfig"}}'
spec:
  selector:
    app: "innovi-portal-argo"
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
  type: NodePort
