apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-virtapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-virtapp
  template:
    metadata:
      labels:
        app: wordpress-virtapp
    spec:
      containers:
      - name: wordpress
        image: virtapp/wordpress-virtapp:0.15
        resources:
            requests:
              memory: "1Gi"
              cpu: 1
            limits:
              cpu: 4
              memory: "2Gi"
        ports:
        - containerPort: 80
        env:
            - name: WORDPRESS_DB_HOST
              value: mariadb-galera
            - name: WORDPRESS_DB_NAME
              value: virtapp_io
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
      restartPolicy: Always
      nodeSelector: {}
        #node-role.kubernetes.io/master: "true"
 
 
---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-virtapp
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: wordpress-virtapp
  
