apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-argo
  labels:
    app: portal-argo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portal-argo
  template:
    metadata:
      labels:
        app: portal-argo
    spec:
      containers:
      - name: portal-argo
        image: virtapp/portal-argo:2.1
        envFrom: 
        - configMapRef:
            name: argo-config
        ports:
          - name: portal-port
            containerPort: 80
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool



---
apiVersion: v1
kind: Service
metadata:
  name: portal-argo
  namespace: default
  labels:
    app: "portal-argo"
  annotations: {}
    #cloud.google.com/neg: '{"ingress": true}'
    #beta.cloud.google.com/backend-config: '{"ports": {"8080":"portal-argo-backendconfig"}}'
spec:
  selector:
    app: "portal-argo"
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: NodePort
