apiVersion: apps/v1
kind: Deployment
metadata:
  name: innovi-portal-test
  labels:
    app: innovi-portal-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: innovi-portal-test
  template:
    metadata:
      labels:
        app: innovi-portal-test
    spec:
      containers:
      - name: innovi-portal-test
        image: agentvi/innovi-portal:latest
        envFrom: 
        - configMapRef:
            name: innovi-portal-config
        ports:
          - name: portal-port
            containerPort: 8082
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
