
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: global-registry.virtapp.io/library/apache-php:7.1
        ports:
          - name: http-port
            containerPort: 80
      restartPolicy: Always
      nodeSelector: {}
        

---

kind: Service
apiVersion: v1
metadata:
  name: apache
spec:
  selector:
    app: apache
  type: ClusterIP
  ports:
    - name: http-port
      port: 8080
      targetPort: 80
